### ISSUE TITLE
Adding a prefix of $, @, # doesn't work 

### ISSUE THREAD

**Issue by audreykoz** [gimatdinov/gimatdinov.archiannotations#2]
Hi, 
So I believe the plugin is installed correctly, as the "Annotations" plugin preference menu is available from Archi's settings, however whenever I add "$foo" or the other prefix options as a property to an element it doesn't display in the view. Am I missing something? 
Thanks! 
-Audrey

**Comment by gimatdinov** [comment]
Hi,
You may be using another plugin (like [specialization-plugin](https://github.com/archi-contribs/specialization-plugin)) that overloads base elements of the Archi metamodel.
These plugins are not compatible with each other.

**Comment by audreykoz** [comment]
Oh okay, thanks! I'll have to try out the plugins independently.
